export enum catalogEnum {
  MEDICO = 'Médico',
  PSICOLOGO = 'Psicólogo',
  VETERINARIO = 'Veterinario',
  ARQUITECTO = 'Arquitecto',
  MAESTRO = 'Maestro',
  DISENADOR = 'Diseñador',
  COCINERO = 'Cocinero',
  DENTISTA = 'Dentista',
  INFORMATICA = 'Informática',
  ALBANILERIA = 'Albañilería',
  VENDEDORES = 'Vendedores',
  CARPINTERIA = 'Carpintería',
  MECANICA = 'Mecánica',
  PINTURA = 'Pintura',
  HERRERIA = 'Herrería',
  JARDINERIA = 'Jardinería',
  PLOMERIA = 'Plomería',
  ELECTRICIDAD = 'Electricidad',
  CLASESEXTRACURRICULARES = 'Clases extracurriculares',
  SASTRERIA = 'Costurería / Sastrería',
}
