export enum catalogEnum {
  MEDICO = 'Medico',
  PSICOLOGO = 'Psicologo',
  VETERINARIO = 'Veterinario',
  ARQUITECTO = 'Arquitecto',
  MAESTRO = 'Maestro',
  DISENADOR = 'Diseñador',
  COCINERO = 'Cocinero',
  DENTISTA = 'Dentista',
  INFORMATICA = 'Informatica',
  ALBANILERIA = 'Albañileria',
  VENDEDORES = 'Vendedores',
  CARPINTERIA = 'Carpinteria',
  MECANICA = 'Mecanica',
  PINTURA = 'Pintura',
  HERRERIA = 'Herreria',
  JARDINERIA = 'Jardineria',
  PLOMERIA = 'Plomeria',
  ELECTRICIDAD = 'Electricidad',
  CLASESEXTRACURRICULARES = 'Clases extracurriculares',
  SASTRERIA = 'Costureria / Sastreria',
}
