version: '3.8'

services:
  db:
    image: postgres:14.3
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
      POSTGRES_DB: "${DB_NAME}"
    container_name: ttdb
    volumes:
      - ./postgres:/var/lib/postgresql/data

  api:
    build: .
    depends_on:
      - db
    networks:
      - db
    ports:
      - 3001:3000